"""media_assets 媒体库图床表

Revision ID: 4765353596b2
Revises: b2e62d70289c
Create Date: 2026-07-20 11:24:41.334710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel autogen 会产出 sqlmodel.sql.sqltypes.AutoString 等类型
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '4765353596b2'
down_revision: Union[str, Sequence[str], None] = 'b2e62d70289c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 幂等守卫（仓内约定，同 jobs/未读两表迁移）：运行期 create_all 可能抢先建好
    # media_assets（老库收养场景）——已存在则跳过。
    if "media_assets" in inspect(op.get_bind()).get_table_names():
        return
    _create_media_assets()


def _create_media_assets() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('url_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mime', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ext', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('url_hash')
    )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_assets_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_assets_status'))
        batch_op.drop_index(batch_op.f('ix_media_assets_content_hash'))

    op.drop_table('media_assets')
    # ### end Alembic commands ###
