"""baseline schema

Revision ID: 5ee31a7c5393
Revises: 
Create Date: 2026-07-01 09:16:57.608287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel autogen 会产出 sqlmodel.sql.sqltypes.AutoString 等类型


# revision identifiers, used by Alembic.
revision: str = '5ee31a7c5393'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_username'), ['username'], unique=False)

    op.create_table('app_settings',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('articles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publish_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetch_run_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('job_run_id', sa.Integer(), nullable=True),
    sa.Column('source_group_id', sa.Integer(), nullable=True),
    sa.Column('run_scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('has_content', sa.Boolean(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extensions_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_vectorized', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_fetch_run_id'), ['fetch_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_is_vectorized'), ['is_vectorized'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_job_run_id'), ['job_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_publish_date'), ['publish_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_run_scope'), ['run_scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_source_group_id'), ['source_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_title'), ['title'], unique=False)

    op.create_table('collection_job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('run_scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('child_run_ids_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ended_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('saved_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_job_runs_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_job_runs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_job_runs_run_scope'), ['run_scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_job_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_job_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_job_runs_trigger_type'), ['trigger_type'], unique=False)

    op.create_table('collection_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('fetcher_ids_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('params_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('per_fetcher_params_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cron_expr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('per_fetcher_cron_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('downstream_policy_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('legacy_task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_jobs_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_jobs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_jobs_legacy_task_id'), ['legacy_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_jobs_name'), ['name'], unique=False)

    op.create_table('fetch_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fetcher_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('job_run_id', sa.Integer(), nullable=True),
    sa.Column('source_group_id', sa.Integer(), nullable=True),
    sa.Column('run_scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('params_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ended_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('saved_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fetch_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fetch_runs_fetcher_id'), ['fetcher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetch_runs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetch_runs_job_run_id'), ['job_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetch_runs_run_scope'), ['run_scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetch_runs_source_group_id'), ['source_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetch_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetch_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetch_runs_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetch_runs_trigger_type'), ['trigger_type'], unique=False)

    op.create_table('fetch_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fetcher_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cron_expr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('params_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fetch_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fetch_tasks_fetcher_id'), ['fetcher_id'], unique=False)

    op.create_table('login_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_username'), ['username'], unique=False)

    op.create_table('node_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetcher_ids_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('params_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('per_fetcher_params_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cron_expr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('per_fetcher_cron_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_groups_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_groups_name'), ['name'], unique=False)

    op.create_table('reader_favorites',
    sa.Column('owner_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('article_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('owner_username', 'article_id')
    )
    with op.batch_alter_table('reader_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reader_favorites_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reader_favorites_created_at'), ['created_at'], unique=False)

    op.create_table('reader_feed_tokens',
    sa.Column('owner_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('owner_username')
    )
    with op.batch_alter_table('reader_feed_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reader_feed_tokens_token_hash'), ['token_hash'], unique=False)

    op.create_table('reader_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reads', sa.Integer(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reader_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reader_reads_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_reader_reads_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reader_reads_username'), ['username'], unique=False)

    op.create_table('reader_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filters_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivery_policy_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reader_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reader_subscriptions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_reader_subscriptions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_reader_subscriptions_owner_username'), ['owner_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_reader_subscriptions_token_hash'), ['token_hash'], unique=False)

    op.create_table('source_configs',
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetcher_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provenance_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_tags_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signal_strength', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('noise_risk', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetch_reliability', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fetch_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('cron_expr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('params_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    with op.batch_alter_table('source_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_configs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_configs_fetch_reliability'), ['fetch_reliability'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_configs_fetcher_id'), ['fetcher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_configs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_configs_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_configs_noise_risk'), ['noise_risk'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_configs_provenance_tier'), ['provenance_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_configs_signal_strength'), ['signal_strength'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_configs_source_brand'), ['source_brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_configs_source_channel'), ['source_channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_configs_source_owner'), ['source_owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_configs_source_scope'), ['source_scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_configs_source_type'), ['source_type'], unique=False)

    op.create_table('source_states',
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetcher_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_completed_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_success_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_failure_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_run_id', sa.Integer(), nullable=True),
    sa.Column('last_cursor_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_cursor_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_content_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('success_runs', sa.Integer(), nullable=False),
    sa.Column('failed_runs', sa.Integer(), nullable=False),
    sa.Column('latest_fetched_count', sa.Integer(), nullable=False),
    sa.Column('latest_saved_count', sa.Integer(), nullable=False),
    sa.Column('latest_skipped_count', sa.Integer(), nullable=False),
    sa.Column('latest_error_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latest_error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    with op.batch_alter_table('source_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_states_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_states_fetcher_id'), ['fetcher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_states_last_cursor_date'), ['last_cursor_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_states_last_failure_at'), ['last_failure_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_states_last_run_id'), ['last_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_states_last_started_at'), ['last_started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_states_last_success_at'), ['last_success_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_states_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ai_beta_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_translate_count', sa.Integer(), nullable=False),
    sa.Column('ai_ask_count', sa.Integer(), nullable=False),
    sa.Column('ai_last_used_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_ai_beta_enabled'), ['ai_beta_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_ai_beta_enabled'))

    op.drop_table('users')
    with op.batch_alter_table('source_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_states_status'))
        batch_op.drop_index(batch_op.f('ix_source_states_last_success_at'))
        batch_op.drop_index(batch_op.f('ix_source_states_last_started_at'))
        batch_op.drop_index(batch_op.f('ix_source_states_last_run_id'))
        batch_op.drop_index(batch_op.f('ix_source_states_last_failure_at'))
        batch_op.drop_index(batch_op.f('ix_source_states_last_cursor_date'))
        batch_op.drop_index(batch_op.f('ix_source_states_fetcher_id'))
        batch_op.drop_index(batch_op.f('ix_source_states_content_type'))

    op.drop_table('source_states')
    with op.batch_alter_table('source_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_configs_source_type'))
        batch_op.drop_index(batch_op.f('ix_source_configs_source_scope'))
        batch_op.drop_index(batch_op.f('ix_source_configs_source_owner'))
        batch_op.drop_index(batch_op.f('ix_source_configs_source_channel'))
        batch_op.drop_index(batch_op.f('ix_source_configs_source_brand'))
        batch_op.drop_index(batch_op.f('ix_source_configs_signal_strength'))
        batch_op.drop_index(batch_op.f('ix_source_configs_provenance_tier'))
        batch_op.drop_index(batch_op.f('ix_source_configs_noise_risk'))
        batch_op.drop_index(batch_op.f('ix_source_configs_name'))
        batch_op.drop_index(batch_op.f('ix_source_configs_is_active'))
        batch_op.drop_index(batch_op.f('ix_source_configs_fetcher_id'))
        batch_op.drop_index(batch_op.f('ix_source_configs_fetch_reliability'))
        batch_op.drop_index(batch_op.f('ix_source_configs_category'))

    op.drop_table('source_configs')
    with op.batch_alter_table('reader_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reader_subscriptions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_reader_subscriptions_owner_username'))
        batch_op.drop_index(batch_op.f('ix_reader_subscriptions_name'))
        batch_op.drop_index(batch_op.f('ix_reader_subscriptions_is_active'))

    op.drop_table('reader_subscriptions')
    with op.batch_alter_table('reader_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reader_reads_username'))
        batch_op.drop_index(batch_op.f('ix_reader_reads_source_id'))
        batch_op.drop_index(batch_op.f('ix_reader_reads_day'))

    op.drop_table('reader_reads')
    with op.batch_alter_table('reader_feed_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reader_feed_tokens_token_hash'))

    op.drop_table('reader_feed_tokens')
    with op.batch_alter_table('reader_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reader_favorites_created_at'))
        batch_op.drop_index(batch_op.f('ix_reader_favorites_article_id'))

    op.drop_table('reader_favorites')
    with op.batch_alter_table('node_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_groups_name'))
        batch_op.drop_index(batch_op.f('ix_node_groups_is_active'))

    op.drop_table('node_groups')
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_events_username'))
        batch_op.drop_index(batch_op.f('ix_login_events_at'))

    op.drop_table('login_events')
    with op.batch_alter_table('fetch_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fetch_tasks_fetcher_id'))

    op.drop_table('fetch_tasks')
    with op.batch_alter_table('fetch_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fetch_runs_trigger_type'))
        batch_op.drop_index(batch_op.f('ix_fetch_runs_task_id'))
        batch_op.drop_index(batch_op.f('ix_fetch_runs_status'))
        batch_op.drop_index(batch_op.f('ix_fetch_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_fetch_runs_source_group_id'))
        batch_op.drop_index(batch_op.f('ix_fetch_runs_run_scope'))
        batch_op.drop_index(batch_op.f('ix_fetch_runs_job_run_id'))
        batch_op.drop_index(batch_op.f('ix_fetch_runs_job_id'))
        batch_op.drop_index(batch_op.f('ix_fetch_runs_fetcher_id'))

    op.drop_table('fetch_runs')
    with op.batch_alter_table('collection_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_jobs_name'))
        batch_op.drop_index(batch_op.f('ix_collection_jobs_legacy_task_id'))
        batch_op.drop_index(batch_op.f('ix_collection_jobs_is_active'))
        batch_op.drop_index(batch_op.f('ix_collection_jobs_group_id'))

    op.drop_table('collection_jobs')
    with op.batch_alter_table('collection_job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_job_runs_trigger_type'))
        batch_op.drop_index(batch_op.f('ix_collection_job_runs_status'))
        batch_op.drop_index(batch_op.f('ix_collection_job_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_collection_job_runs_run_scope'))
        batch_op.drop_index(batch_op.f('ix_collection_job_runs_job_id'))
        batch_op.drop_index(batch_op.f('ix_collection_job_runs_group_id'))

    op.drop_table('collection_job_runs')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_title'))
        batch_op.drop_index(batch_op.f('ix_articles_source_id'))
        batch_op.drop_index(batch_op.f('ix_articles_source_group_id'))
        batch_op.drop_index(batch_op.f('ix_articles_run_scope'))
        batch_op.drop_index(batch_op.f('ix_articles_publish_date'))
        batch_op.drop_index(batch_op.f('ix_articles_job_run_id'))
        batch_op.drop_index(batch_op.f('ix_articles_job_id'))
        batch_op.drop_index(batch_op.f('ix_articles_is_vectorized'))
        batch_op.drop_index(batch_op.f('ix_articles_fetch_run_id'))
        batch_op.drop_index(batch_op.f('ix_articles_content_type'))

    op.drop_table('articles')
    op.drop_table('app_settings')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_username'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_purpose'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_day'))

    op.drop_table('ai_usage')
    # ### end Alembic commands ###
