"""engage wave feedbacks announcements

Revision ID: 5f1e4b31e27a
Revises: 4765353596b2
Create Date: 2026-07-23 21:21:12.185001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel autogen 会产出 sqlmodel.sql.sqltypes.AutoString 等类型
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '5f1e4b31e27a'
down_revision: Union[str, Sequence[str], None] = '4765353596b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 幂等守卫(仓内约定,同 jobs/未读/media_assets 迁移):运行期 create_all 可能
    # 抢先建好这些表(老库收养场景)——逐表判存在则跳过。
    existing = set(inspect(op.get_bind()).get_table_names())
    if "announcement_dismissals" not in existing:
        _create_announcement_dismissals()
    if "announcements" not in existing:
        _create_announcements()
    if "feedbacks" not in existing:
        _create_feedbacks()


def _create_announcement_dismissals() -> None:
    op.create_table('announcement_dismissals',
    sa.Column('owner_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('dismissed_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('owner_username', 'announcement_id')
    )
    with op.batch_alter_table('announcement_dismissals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcement_dismissals_announcement_id'), ['announcement_id'], unique=False)


def _create_announcements() -> None:
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_level'), ['level'], unique=False)


def _create_feedbacks() -> None:
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedbacks_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_owner_username'), ['owner_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedbacks_status'))
        batch_op.drop_index(batch_op.f('ix_feedbacks_owner_username'))
        batch_op.drop_index(batch_op.f('ix_feedbacks_created_at'))
        batch_op.drop_index(batch_op.f('ix_feedbacks_category'))

    op.drop_table('feedbacks')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_level'))
        batch_op.drop_index(batch_op.f('ix_announcements_is_active'))
        batch_op.drop_index(batch_op.f('ix_announcements_created_at'))

    op.drop_table('announcements')
    with op.batch_alter_table('announcement_dismissals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_dismissals_announcement_id'))

    op.drop_table('announcement_dismissals')
    # ### end Alembic commands ###
