"""add articles.index_status enum

Revision ID: 8bba6f81b240
Revises: c8df1ef41529
Create Date: 2026-07-03 09:52:11.194037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel autogen 会产出 sqlmodel.sql.sqltypes.AutoString 等类型
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '8bba6f81b240'
down_revision: Union[str, Sequence[str], None] = 'c8df1ef41529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """加 index_status 列并从 is_vectorized 回填；对已有列/索引幂等跳过。"""
    insp = inspect(op.get_bind())
    columns = {c["name"] for c in insp.get_columns("articles")}
    if "index_status" not in columns:
        # 带 server_default 以兼容存量行（否则 NOT NULL 新列在有数据表上失败）。
        with op.batch_alter_table('articles', schema=None) as batch_op:
            batch_op.add_column(sa.Column(
                'index_status', sqlmodel.sql.sqltypes.AutoString(),
                nullable=False, server_default='pending',
            ))
        # 回填：已向量化 → indexed；其余保持 pending（server_default）。
        op.execute("UPDATE articles SET index_status='indexed' WHERE is_vectorized=1")

    indexes = {i["name"] for i in inspect(op.get_bind()).get_indexes("articles")}
    if "ix_articles_index_status" not in indexes:
        op.create_index(op.f('ix_articles_index_status'), 'articles', ['index_status'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_index_status'))
        batch_op.drop_column('index_status')

    # ### end Alembic commands ###
