"""article analysis and taxonomy schema

Revision ID: a3f64d8c2e11
Revises: d9de7994582c
Create Date: 2026-09-01 17:06:16.311313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel autogen 会产出 sqlmodel.sql.sqltypes.AutoString 等类型
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'a3f64d8c2e11'
down_revision: Union[str, Sequence[str], None] = 'd9de7994582c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Runtime create_all() may have created the new tables before a legacy DB is
    # adopted by Alembic. Accept the complete current shape, but reject a partial
    # shape instead of silently hiding a broken deployment.
    existing = set(inspect(op.get_bind()).get_table_names())
    expected = {
        "cms_tags", "taxonomy_versions", "article_analyses",
        "article_analysis_attempts", "article_tag_assignments",
        "cms_tag_aliases", "cms_tag_candidates",
        "cms_tag_candidate_evidence", "cms_tag_events", "tag_retag_jobs",
        "duplicate_groups", "duplicate_group_members",
    }
    if expected.issubset(existing):
        _ensure_source_config_ai_analysis_enabled()
        return
    overlap = expected & existing
    if overlap:
        raise RuntimeError(f"partial article-analysis schema exists: {sorted(overlap)}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_zh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('replacement_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_selectable', sa.Boolean(), nullable=False),
    sa.Column('filterable', sa.Boolean(), nullable=False),
    sa.Column('recommendable', sa.Boolean(), nullable=False),
    sa.Column('activation_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('taxonomy_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("activation_mode IN ('manual','automatic')", name='ck_cms_tags_activation_mode'),
    sa.CheckConstraint("kind IN ('topic','industry','entity')", name='ck_cms_tags_kind'),
    sa.CheckConstraint("status IN ('draft','active','deprecated','merged')", name='ck_cms_tags_status'),
    sa.ForeignKeyConstraint(['parent_id'], ['cms_tags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['replacement_id'], ['cms_tags.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_cms_tags_code'),
    sa.UniqueConstraint('kind', 'normalized_name', name='uq_cms_tags_kind_normalized_name')
    )
    with op.batch_alter_table('cms_tags', schema=None) as batch_op:
        batch_op.create_index('ix_cms_tags_kind_status_user_selectable', ['kind', 'status', 'user_selectable'], unique=False)
        batch_op.create_index('uq_cms_tags_entity_external_key', ['external_key'], unique=True, sqlite_where=sa.text("kind = 'entity' AND external_key IS NOT NULL"))

    op.create_table('taxonomy_versions',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("status IN ('draft','active','retired')", name='ck_taxonomy_versions_status'),
    sa.PrimaryKeyConstraint('version')
    )
    with op.batch_alter_table('taxonomy_versions', schema=None) as batch_op:
        batch_op.create_index('uq_taxonomy_versions_one_active', ['status'], unique=True, sqlite_where=sa.text("status = 'active'"))

    op.create_table('article_analyses',
    sa.Column('article_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tagging_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('dimension_scores_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('one_sentence_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_genre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_features_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entities_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_tag_id', sa.Integer(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scoring_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('taxonomy_version', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_attempt_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lease_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lease_expires_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('analyzed_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tagged_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("content_genre IS NULL OR content_genre IN ('model_release','product_update','open_source_update','research_paper','tutorial','opinion','industry_news','conference','social_discussion','aggregation','security_incident','regulation','other')", name='ck_article_analyses_content_genre'),
    sa.CheckConstraint("status IN ('pending','running','succeeded','failed','skipped','timeout')", name='ck_article_analyses_status'),
    sa.CheckConstraint("tagging_status IN ('pending','succeeded','partial','failed')", name='ck_article_analyses_tagging_status'),
    sa.CheckConstraint('quality_score IS NULL OR (quality_score >= 1.0 AND quality_score <= 10.0)', name='ck_article_analyses_quality_score'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_tag_id'], ['cms_tags.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('article_id')
    )
    with op.batch_alter_table('article_analyses', schema=None) as batch_op:
        batch_op.create_index('ix_article_analyses_content_hash', ['content_hash'], unique=False)
        batch_op.create_index('ix_article_analyses_scan', ['status', 'next_attempt_at', 'lease_expires_at'], unique=False)

    op.create_table('article_analysis_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scoring_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('taxonomy_version', sa.Integer(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ended_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result_summary_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("operation IN ('full_analysis','retag_only')", name='ck_article_analysis_attempts_operation'),
    sa.CheckConstraint("status IN ('running','succeeded','failed','skipped','timeout')", name='ck_article_analysis_attempts_status'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'attempt_no', name='uq_article_analysis_attempt_number')
    )
    with op.batch_alter_table('article_analysis_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_article_analysis_attempts_article_created', ['article_id', 'created_at'], unique=False)

    op.create_table('article_tag_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tag_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('assignment_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('taxonomy_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("assignment_source IN ('llm','manual','rule','migration')", name='ck_article_tag_assignments_source'),
    sa.CheckConstraint("tag_kind IN ('topic','industry','entity')", name='ck_article_tag_assignments_kind'),
    sa.CheckConstraint('relevance >= 0.0 AND relevance <= 1.0', name='ck_article_tag_assignments_relevance'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['cms_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'tag_id', name='uq_article_tag_assignments_article_tag')
    )
    with op.batch_alter_table('article_tag_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_article_tag_assignments_tag_article', ['tag_id', 'article_id'], unique=False)
        batch_op.create_index('uq_article_tag_assignments_primary_facet', ['article_id', 'tag_kind'], unique=True, sqlite_where=sa.text('is_primary = 1'))

    op.create_table('cms_tag_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alias_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("alias_type IN ('synonym','abbreviation','former_name','translation','misspelling')", name='ck_cms_tag_aliases_type'),
    sa.CheckConstraint("kind IN ('topic','industry','entity')", name='ck_cms_tag_aliases_kind'),
    sa.ForeignKeyConstraint(['tag_id'], ['cms_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'normalized_alias', name='uq_cms_tag_aliases_kind_normalized')
    )
    with op.batch_alter_table('cms_tag_aliases', schema=None) as batch_op:
        batch_op.create_index('ix_cms_tag_aliases_tag_id', ['tag_id'], unique=False)

    op.create_table('cms_tag_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proposed_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('support_article_count_7d', sa.Integer(), nullable=False),
    sa.Column('support_article_count_30d', sa.Integer(), nullable=False),
    sa.Column('distinct_source_count_7d', sa.Integer(), nullable=False),
    sa.Column('distinct_source_count_30d', sa.Integer(), nullable=False),
    sa.Column('distinct_day_count_7d', sa.Integer(), nullable=False),
    sa.Column('distinct_day_count_30d', sa.Integer(), nullable=False),
    sa.Column('mean_confidence', sa.Float(), nullable=False),
    sa.Column('nearest_tag_id', sa.Integer(), nullable=True),
    sa.Column('nearest_similarity', sa.Float(), nullable=True),
    sa.Column('resolution_tag_id', sa.Integer(), nullable=True),
    sa.Column('sample_article_ids_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risk_flags_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_seen_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_seen_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("proposed_kind IN ('topic','industry','entity')", name='ck_cms_tag_candidates_kind'),
    sa.CheckConstraint("status IN ('candidate','reviewing','activated','merged','rejected')", name='ck_cms_tag_candidates_status'),
    sa.CheckConstraint('mean_confidence >= 0.0 AND mean_confidence <= 1.0', name='ck_cms_tag_candidates_mean_confidence'),
    sa.CheckConstraint('nearest_similarity IS NULL OR (nearest_similarity >= 0.0 AND nearest_similarity <= 1.0)', name='ck_cms_tag_candidates_nearest_similarity'),
    sa.ForeignKeyConstraint(['nearest_tag_id'], ['cms_tags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolution_tag_id'], ['cms_tags.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposed_kind', 'normalized_label', name='uq_cms_tag_candidates_kind_normalized')
    )
    with op.batch_alter_table('cms_tag_candidates', schema=None) as batch_op:
        batch_op.create_index('ix_cms_tag_candidates_kind_status', ['proposed_kind', 'status'], unique=False)
        batch_op.create_index('ix_cms_tag_candidates_status_last_seen', ['status', 'last_seen_at'], unique=False)

    op.create_table('cms_tag_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_tag_id', sa.Integer(), nullable=True),
    sa.Column('target_tag_id', sa.Integer(), nullable=True),
    sa.Column('actor_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("action IN ('activate','rename','merge','deprecate','reject','change_flags')", name='ck_cms_tag_events_action'),
    sa.CheckConstraint("actor_type IN ('user','system')", name='ck_cms_tag_events_actor_type'),
    sa.ForeignKeyConstraint(['source_tag_id'], ['cms_tags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_tag_id'], ['cms_tags.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cms_tag_events', schema=None) as batch_op:
        batch_op.create_index('ix_cms_tag_events_created_at', ['created_at'], unique=False)

    op.create_table('duplicate_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('strategy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('representative_article_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['representative_article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint', name='uq_duplicate_groups_fingerprint')
    )
    op.create_table('cms_tag_candidate_evidence',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_owner_or_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_candidate_evidence_confidence'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['cms_tag_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id', 'article_id')
    )
    with op.batch_alter_table('cms_tag_candidate_evidence', schema=None) as batch_op:
        batch_op.create_index('ix_cms_tag_candidate_evidence_article_id', ['article_id'], unique=False)

    op.create_table('duplicate_group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('is_representative', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint('similarity IS NULL OR (similarity >= 0.0 AND similarity <= 1.0)', name='ck_duplicate_group_members_similarity'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['duplicate_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'article_id'),
    sa.UniqueConstraint('article_id', name='uq_duplicate_group_members_article')
    )
    op.create_table('tag_retag_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('taxonomy_version', sa.Integer(), nullable=False),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cursor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('affected_count', sa.Integer(), nullable=False),
    sa.Column('succeeded_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lease_expires_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("operation IN ('full_analysis','retag_only')", name='ck_tag_retag_jobs_operation'),
    sa.CheckConstraint("status IN ('queued','running','succeeded','partial_failed','failed','cancelled')", name='ck_tag_retag_jobs_status'),
    sa.ForeignKeyConstraint(['event_id'], ['cms_tag_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['taxonomy_version'], ['taxonomy_versions.version'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tag_retag_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_tag_retag_jobs_claim', ['status', 'lease_expires_at'], unique=False)

    _ensure_source_config_ai_analysis_enabled()

    # ### end Alembic commands ###


def _ensure_source_config_ai_analysis_enabled() -> None:
    columns = {
        column["name"]
        for column in inspect(op.get_bind()).get_columns("source_configs")
    }
    if "ai_analysis_enabled" not in columns:
        with op.batch_alter_table("source_configs", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "ai_analysis_enabled",
                    sa.Boolean(),
                    nullable=False,
                    server_default=sa.text("1"),
                )
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_configs', schema=None) as batch_op:
        batch_op.drop_column('ai_analysis_enabled')

    with op.batch_alter_table('tag_retag_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_tag_retag_jobs_claim')

    op.drop_table('tag_retag_jobs')
    op.drop_table('duplicate_group_members')
    with op.batch_alter_table('cms_tag_candidate_evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_cms_tag_candidate_evidence_article_id')

    op.drop_table('cms_tag_candidate_evidence')
    op.drop_table('duplicate_groups')
    with op.batch_alter_table('cms_tag_events', schema=None) as batch_op:
        batch_op.drop_index('ix_cms_tag_events_created_at')

    op.drop_table('cms_tag_events')
    with op.batch_alter_table('cms_tag_candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_cms_tag_candidates_status_last_seen')
        batch_op.drop_index('ix_cms_tag_candidates_kind_status')

    op.drop_table('cms_tag_candidates')
    with op.batch_alter_table('cms_tag_aliases', schema=None) as batch_op:
        batch_op.drop_index('ix_cms_tag_aliases_tag_id')

    op.drop_table('cms_tag_aliases')
    with op.batch_alter_table('article_tag_assignments', schema=None) as batch_op:
        batch_op.drop_index('uq_article_tag_assignments_primary_facet', sqlite_where=sa.text('is_primary = 1'))
        batch_op.drop_index('ix_article_tag_assignments_tag_article')

    op.drop_table('article_tag_assignments')
    with op.batch_alter_table('article_analysis_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_article_analysis_attempts_article_created')

    op.drop_table('article_analysis_attempts')
    with op.batch_alter_table('article_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_article_analyses_scan')
        batch_op.drop_index('ix_article_analyses_content_hash')

    op.drop_table('article_analyses')
    with op.batch_alter_table('taxonomy_versions', schema=None) as batch_op:
        batch_op.drop_index('uq_taxonomy_versions_one_active', sqlite_where=sa.text("status = 'active'"))

    op.drop_table('taxonomy_versions')
    with op.batch_alter_table('cms_tags', schema=None) as batch_op:
        batch_op.drop_index('uq_cms_tags_entity_external_key', sqlite_where=sa.text("kind = 'entity' AND external_key IS NOT NULL"))
        batch_op.drop_index('ix_cms_tags_kind_status_user_selectable')

    op.drop_table('cms_tags')
    # ### end Alembic commands ###
