"""reader unread state and read cursors

Revision ID: b2e62d70289c
Revises: e7a3c19b5d02
Create Date: 2026-07-16 00:56:50.974472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel autogen 会产出 sqlmodel.sql.sqltypes.AutoString 等类型
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'b2e62d70289c'
down_revision: Union[str, Sequence[str], None] = 'e7a3c19b5d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 幂等守卫：运行期 create_all 可能抢先建好两表（与 create_all 共存的设计，
    # 同 jobs 表迁移的约定）——已存在则逐表跳过；若抢先建出的是早期形状
    # （无 is_read 列），则补列对齐（列缺补列，存量行按显式已读回填 =1）。
    bind = op.get_bind()
    existing = set(inspect(bind).get_table_names())
    if "reader_article_read_states" not in existing:
        _create_read_states()
    else:
        columns = {c["name"] for c in inspect(bind).get_columns("reader_article_read_states")}
        if "is_read" not in columns:
            with op.batch_alter_table("reader_article_read_states", schema=None) as batch_op:
                batch_op.add_column(
                    sa.Column("is_read", sa.Boolean(), nullable=False, server_default=sa.text("1"))
                )
    if "reader_read_cursors" not in existing:
        _create_read_cursors()


def _create_read_states() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reader_article_read_states',
    sa.Column('owner_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('article_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('owner_username', 'article_id')
    )
    with op.batch_alter_table('reader_article_read_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reader_article_read_states_article_id'), ['article_id'], unique=False)


def _create_read_cursors() -> None:
    op.create_table('reader_read_cursors',
    sa.Column('owner_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mark_read_before', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('owner_username', 'source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reader_read_cursors')
    with op.batch_alter_table('reader_article_read_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reader_article_read_states_article_id'))

    op.drop_table('reader_article_read_states')
    # ### end Alembic commands ###
