"""user interests and personal digest schema

Revision ID: b7e29d4f6a30
Revises: a3f64d8c2e11
Create Date: 2026-09-01 17:07:56.925327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel autogen 会产出 sqlmodel.sql.sqltypes.AutoString 等类型
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'b7e29d4f6a30'
down_revision: Union[str, Sequence[str], None] = 'a3f64d8c2e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # DatabaseStorage.create_all() may win the startup race on an adopted legacy
    # database. A complete pre-created shape is safe; a partial shape is not.
    existing = set(inspect(op.get_bind()).get_table_names())
    expected = {
        "user_interest_tags",
        "personal_digest_editions",
        "personal_digest_items",
    }
    if expected.issubset(existing):
        return
    overlap = expected & existing
    if overlap:
        raise RuntimeError(f"partial personal-digest schema exists: {sorted(overlap)}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_digest_editions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_open_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('check_after', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cutoff_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deadline_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expected_source_ids_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_source_ids_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_state_snapshot_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('taxonomy_version', sa.Integer(), nullable=False),
    sa.Column('interest_version', sa.Integer(), nullable=False),
    sa.Column('generation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('degraded_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("generation_reason IN ('scheduled','first_open','interest_changed','subscription_changed','manual_rebuild','recovery')", name='ck_personal_digest_editions_generation_reason'),
    sa.CheckConstraint("status IN ('pending','generating','ready','degraded','failed')", name='ck_personal_digest_editions_status'),
    sa.CheckConstraint('revision >= 1', name='ck_personal_digest_editions_revision'),
    sa.ForeignKeyConstraint(['owner_username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_username', 'report_date', 'revision', name='uq_personal_digest_editions_owner_date_revision')
    )
    with op.batch_alter_table('personal_digest_editions', schema=None) as batch_op:
        batch_op.create_index('ix_personal_digest_editions_owner_date', ['owner_username', 'report_date'], unique=False)
        batch_op.create_index('ix_personal_digest_editions_ready_scan', ['status', 'check_after'], unique=False)

    op.create_table('user_interest_tags',
    sa.Column('owner_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('stance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("priority IN ('normal','high')", name='ck_user_interest_tags_priority'),
    sa.CheckConstraint("source = 'explicit'", name='ck_user_interest_tags_source'),
    sa.CheckConstraint("stance IN ('follow','mute')", name='ck_user_interest_tags_stance'),
    sa.ForeignKeyConstraint(['owner_username'], ['users.username'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['cms_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_username', 'tag_id')
    )
    with op.batch_alter_table('user_interest_tags', schema=None) as batch_op:
        batch_op.create_index('ix_user_interest_tags_owner_stance', ['owner_username', 'stance'], unique=False)
        batch_op.create_index('ix_user_interest_tags_tag_id', ['tag_id'], unique=False)

    op.create_table('personal_digest_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selection_lane', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quality_score_snapshot', sa.Float(), nullable=True),
    sa.Column('matched_interest_codes_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ranking_features_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('coverage_adjustments_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("selection_lane IN ('interest','quality')", name='ck_personal_digest_items_selection_lane'),
    sa.CheckConstraint('position >= 0', name='ck_personal_digest_items_position'),
    sa.CheckConstraint('quality_score_snapshot IS NULL OR (quality_score_snapshot >= 1.0 AND quality_score_snapshot <= 10.0)', name='ck_personal_digest_items_quality_score'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['edition_id'], ['personal_digest_editions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edition_id', 'position', name='uq_personal_digest_items_edition_position')
    )
    with op.batch_alter_table('personal_digest_items', schema=None) as batch_op:
        batch_op.create_index('ix_personal_digest_items_article_id', ['article_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_digest_items', schema=None) as batch_op:
        batch_op.drop_index('ix_personal_digest_items_article_id')

    op.drop_table('personal_digest_items')
    with op.batch_alter_table('user_interest_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_user_interest_tags_tag_id')
        batch_op.drop_index('ix_user_interest_tags_owner_stance')

    op.drop_table('user_interest_tags')
    with op.batch_alter_table('personal_digest_editions', schema=None) as batch_op:
        batch_op.drop_index('ix_personal_digest_editions_ready_scan')
        batch_op.drop_index('ix_personal_digest_editions_owner_date')

    op.drop_table('personal_digest_editions')
    # ### end Alembic commands ###
