"""Desktop reader main path for #90: brief → article → containers → Discover (Chromium).

The personal brief is generated by the real backend from seeded, already-analysed articles;
no LLM is involved (Chinese titles skip localisation). Personal briefs are a global switch,
so this flow turns it on through the real admin API and restores it afterwards; the other
flows keep landing on the article list.
"""
from __future__ import annotations

from contextlib import contextmanager
import re
import sqlite3
from urllib.parse import urlsplit

from playwright.sync_api import expect

from e2e.mobile_reader import login, observed_page
from e2e.reader_fixture import (ADMIN_USERNAME, BRIEF_FLOOR, BRIEF_SCORES, BULLETIN_COUNT, DESK_USERNAME, PASSWORD,
                                SOURCE_A, SOURCE_B, SOURCE_NAMES, article_title, bulletin_title)


def path_is(path):
    return lambda response: urlsplit(response.url).path == path


@contextmanager
def personal_digest_enabled(browser, base_url):
    context = browser.new_context()
    try:
        response = context.request.post(f"{base_url}/api/auth/login",
                                        data={"username": ADMIN_USERNAME, "password": PASSWORD})
        assert response.ok, response.status

        def set_enabled(value):
            response = context.request.put(f"{base_url}/api/admin/analysis/config",
                                           data={"personal_digest_enabled": value})
            assert response.ok, (response.status, response.text())

        set_enabled(True)
        try:
            yield
        finally:
            set_enabled(False)
    finally:
        context.close()


def brief_titles(page):
    return page.locator(".brief-card:not(.is-skel) .brief-card-title").all_text_contents()


def run_desktop_flows(browser, base_url, database, artifacts, result):
    checks = result.setdefault("checks", [])
    selected = [(f"{SOURCE_A}-{index:02d}", article_title(SOURCE_A, index))
                for index, score in enumerate(BRIEF_SCORES) if score >= BRIEF_FLOOR]
    below_floor = article_title(SOURCE_A, BRIEF_SCORES.index(min(BRIEF_SCORES)))
    with personal_digest_enabled(browser, base_url), \
            observed_page(browser, base_url, artifacts, "desktop", result, desktop=True) as (page, _audit):
        page.goto(base_url)
        with page.expect_response(path_is("/api/reader/briefs/today/ensure"), timeout=30000) as ensured:
            assert login(page, username=DESK_USERNAME).status == 200
        brief = ensured.value.json()
        assert brief["status"] == "ready", brief
        edition = brief["edition"]
        assert [item["article_id"] for item in edition["items"]] == [article_id for article_id, _ in selected], edition
        rail = page.get_by_role("navigation", name="阅读视图")
        expect(rail.get_by_role("button", name="我的早报")).to_have_attribute("aria-pressed", "true", timeout=30000)
        expect(page.locator(".app-arrive")).to_have_count(0, timeout=15000)
        expect(page.locator(".brief-card:not(.is-skel)")).to_have_count(len(selected))
        assert brief_titles(page) == [title for _, title in selected], brief_titles(page)
        expect(page.get_by_text(below_floor, exact=True)).to_have_count(0)
        expect(page.locator(".brief-byline-text")).to_contain_text(f"选出 {len(selected)} 篇")
        page.screenshot(path=str(artifacts / "desktop-brief.png"), animations="disabled")
        checks.append("desktop login lands on a real generated brief: seeded scores ordered, below-floor item absent")

        first_id, first_title = selected[0]
        with page.expect_response(lambda response: response.request.method == "POST"
                                  and urlsplit(response.url).path == f"/api/reader/articles/{first_id}/read") as read:
            page.locator(".brief-card-open", has_text=first_title).click()
        assert read.value.status == 200
        expect(page.locator(".reader-pane h1")).to_have_text(first_title)
        expect(page.locator(".reader-pane")).to_contain_text("阅读章节 24")
        checks.append("opening a brief card shows that article in the reading pane and records the read")

        with page.expect_response(lambda response: urlsplit(response.url).path == "/api/articles"
                                  and "shape=article" in response.url) as listed:
            rail.get_by_role("button", name="文章", exact=True).click()
        items = listed.value.json()["items"]
        assert len(items) == 30 and {item["source_id"] for item in items} == {SOURCE_A}, items
        expect(page.locator(".reader-entry")).to_have_count(30)
        target = article_title(SOURCE_A, 10)
        page.get_by_text(target, exact=True).click()
        expect(page.locator(".reader-pane h1")).to_have_text(target)
        expect(page.locator(".reader-pane")).to_contain_text("阅读章节 24")
        page.screenshot(path=str(artifacts / "desktop-article.png"), animations="disabled")
        checks.append("article container lists the subscribed source from the real API and opens a body")

        with page.expect_response(lambda response: urlsplit(response.url).path == "/api/articles"
                                  and "shape=bulletin" in response.url) as listed:
            rail.get_by_role("button", name="动态", exact=True).click()
        assert len(listed.value.json()["items"]) == BULLETIN_COUNT
        expect(page.locator(".reader-entry")).to_have_count(BULLETIN_COUNT)
        assert page.locator(".reader-entry-title").all_text_contents() == [bulletin_title(i) for i in range(BULLETIN_COUNT)]
        checks.append("bulletin container shows only the subscribed release-note source")

        rail.get_by_role("button", name="发现", exact=True).click()
        discover = page.get_by_role("main", name="发现")
        # Discover inherits the container it was opened from (动态 here).
        shape = discover.get_by_role("group", name="形态筛选")
        expect(shape.get_by_role("button", name="动态", exact=True)).to_have_class(re.compile(r"\bis-on\b"))
        shape.get_by_role("button", name="文章", exact=True).click()
        discover.get_by_label("筛选来源").fill("端到端测试来源")
        card_a = discover.locator(".reader-disc-card", has_text=SOURCE_NAMES[SOURCE_A])
        card_b = discover.locator(".reader-disc-card", has_text=SOURCE_NAMES[SOURCE_B])
        expect(card_a.locator(".reader-disc-sub")).to_contain_text("已订阅")
        expect(card_b.locator(".reader-disc-sub")).to_have_text("订阅")
        with page.expect_response(lambda response: response.request.method == "POST"
                                  and urlsplit(response.url).path == f"/api/reader/sources/{SOURCE_B}/subscribe") as sub:
            card_b.locator(".reader-disc-sub").click()
        assert sub.value.status == 200
        expect(card_b.locator(".reader-disc-sub")).to_contain_text("已订阅")
        page.screenshot(path=str(artifacts / "desktop-discover.png"), animations="disabled")
        with sqlite3.connect(database.as_uri() + "?mode=ro", uri=True) as db:
            rows = db.execute("SELECT filters_json FROM reader_subscriptions WHERE owner_username=? AND is_active=1",
                              (DESK_USERNAME,)).fetchall()
        assert any(SOURCE_B in filters for (filters,) in rows), rows
        checks.append("Discover filters the real catalog and subscribing persists in SQLite")

        # Since v3.51.1 a subscription edit never rebuilds today's edition by itself.
        with page.expect_response(path_is("/api/reader/briefs/today/ensure")) as ensured:
            rail.get_by_role("button", name="我的早报").click()
        again = ensured.value.json()["edition"]
        assert again["revision"] == edition["revision"] and again["scope_stale"] is True, again
        expect(page.locator(".brief-card:not(.is-skel)")).to_have_count(len(selected))
        expect(page.locator(".brief-byline-tail")).to_contain_text("你的订阅已更新")
        checks.append("returning to the brief keeps the edition and offers a rebuild after the subscription change")
